version: '3.8'

services:
  pentoolbox:
    build: .
    container_name: pentoolbox
    ports:
      - "5000:5000"
    volumes:
      - ./reports:/app/reports
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
